services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1932:1932"
    environment:
      REDIS_ENDPOINT: redis:6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - "6379:6379"